version: '3'

services:
  sharepoint-automation:
    build: .
    container_name: excel-to-word-sharepoint
    volumes:
      # Mount for local logs
      - ./logs:/app/logs
      # Mount the temp directory to persist downloaded files between restarts
      - ./temp:/app/temp
      - ${HOME}/.config/rclone/rclone.conf:/tmp/rclone.conf:ro
    restart: always
    environment:
      # Add any needed environment variables here
      # Example: credentials could be passed via environment variables
      - INTERVAL_MINUTES=60
